version: '3.8'
services:
  exchanges_evaluator:
    container_name: exchanges_evaluator_app
    build:
      context: .
    restart: always
    env_file: 
      - ./.env
    ports:
      - '3001:3001'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=750M
      - MAX_EXECUTION_TIME=86400
